// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ePreschool.Infrastructure;

#nullable disable

namespace ePreschool.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220622062551_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ePreschool.Core.Entities.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("IDNumber")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<int>("PreschoolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PreschoolId");

                    b.ToTable("BusinessUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Address = "Sjeverni Logor 12",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            Email = "zemzem_sjeverni@gmail.com",
                            IDNumber = "643218645312",
                            IsDeleted = false,
                            Name = "ZemZem Sjeveni",
                            PhoneNumber = "+387 36 333 333",
                            PostalCode = "88208",
                            PreschoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Address = "Zalik 12b",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            Email = "zemzem_zalik@gmail.com",
                            IDNumber = "985518645312",
                            IsDeleted = false,
                            Name = "ZemZem Zalik",
                            PhoneNumber = "+387 36 111 333",
                            PostalCode = "88208",
                            PreschoolId = 1
                        });
                });

            modelBuilder.Entity("ePreschool.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = true,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Zenica"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Bihać"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Zagreb"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Split"
                        });
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "BIH",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = true,
                            Name = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "HR",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Hrvatska"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "SR",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Srbija"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "CG",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Crna Gora"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "SLO",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Slovenija"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "A",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Austrija"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "MKD",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            IsFavorite = false,
                            Name = "Makedonija"
                        });
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("RoleLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("SignInAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "SuperAdministrator",
                            NormalizedName = "SUPERADMINISTRATOR",
                            SignInAllowed = false
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "2547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Ministry",
                            NormalizedName = "MINISTRY",
                            RoleLevel = 1,
                            SignInAllowed = false
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "3547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "PreschoolAdministrator",
                            NormalizedName = "PRESCHOOLADMINISTRATOR",
                            RoleLevel = 2,
                            SignInAllowed = false
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "4547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "PreschoolManagement",
                            NormalizedName = "PRESCHOOLMANAGEMENT",
                            RoleLevel = 3,
                            SignInAllowed = false
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "5547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "BusinessUnitAdministrator",
                            NormalizedName = "BUSINESSUNITADMINISTRATOR",
                            RoleLevel = 4,
                            SignInAllowed = false
                        },
                        new
                        {
                            Id = 6,
                            ConcurrencyStamp = "6547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "BusinessUnitEmployee",
                            NormalizedName = "BUSINESSUNITEMPLOYEE",
                            RoleLevel = 5,
                            SignInAllowed = false
                        },
                        new
                        {
                            Id = 7,
                            ConcurrencyStamp = "7547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Parent",
                            NormalizedName = "PARENT",
                            RoleLevel = 6,
                            SignInAllowed = false
                        },
                        new
                        {
                            Id = 8,
                            ConcurrencyStamp = "8547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Expert",
                            NormalizedName = "EXPERT",
                            RoleLevel = 7,
                            SignInAllowed = false
                        });
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AlternativePhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CurrentBusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PostCode")
                        .HasColumnType("text");

                    b.Property<int?>("PreschoolId")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoThumbnail")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CurrentBusinessUnitId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PreschoolId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Active = false,
                            CityId = 1,
                            ConcurrencyStamp = "9547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            Email = "admin@preschool.ba",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "PreSchool",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PRESCHOOL.BA",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "/jgjzf1nC8YDuZMV5q0kYrRqIarjCDgWjBERaZiyyO0=",
                            PasswordSalt = "DFQVcTkMv8qWjq/5ars8Eg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Active = false,
                            CityId = 1,
                            ConcurrencyStamp = "9547f983-1707-49d3-9390-5ec84ec35dca",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            Email = "manager@preschool.ba",
                            EmailConfirmed = true,
                            FirstName = "Manager",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "PreSchool",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@PRESCHOOL.BA",
                            NormalizedUserName = "MANAGER",
                            PasswordHash = "/jgjzf1nC8YDuZMV5q0kYrRqIarjCDgWjBERaZiyyO0=",
                            PasswordSalt = "DFQVcTkMv8qWjq/5ars8Eg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "manager"
                        });
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("ApplicationRoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PreschoolId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("PreschoolId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            Id = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 4,
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            Id = 2,
                            IsDeleted = false,
                            PreschoolId = 1
                        });
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentUrl")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionStackTrace")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReferrerUrl")
                        .HasColumnType("text");

                    b.Property<int?>("RowId")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Preschool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("IDNumber")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<bool>("InVatSystem")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("LogoThumbnail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text");

                    b.Property<bool>("VatIncludedInPrice")
                        .HasColumnType("boolean");

                    b.Property<string>("WebPage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Preschools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Address = "Sjeverni Logor 12",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            Email = "zemzem@gmail.com",
                            InVatSystem = false,
                            IsDeleted = false,
                            Name = "ZemZem",
                            PhoneNumber = "+387 36 222 333",
                            PostalCode = "88208",
                            TaxNumber = "65487978654654",
                            VatIncludedInPrice = false
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Address = "Alekse Šantića 5",
                            CreatedAt = new DateTime(2022, 6, 10, 1, 22, 18, 866, DateTimeKind.Local),
                            Email = "djecija.radost@gmail.com",
                            InVatSystem = false,
                            IsDeleted = false,
                            Name = "Djecija radost",
                            PhoneNumber = "+387 36 222 333",
                            PostalCode = "88208",
                            TaxNumber = "65487978654654",
                            VatIncludedInPrice = false
                        });
                });

            modelBuilder.Entity("ePreschool.Core.Entities.BusinessUnit", b =>
                {
                    b.HasOne("ePreschool.Core.Entities.Preschool", "Preschool")
                        .WithMany("BusinessUnits")
                        .HasForeignKey("PreschoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preschool");
                });

            modelBuilder.Entity("ePreschool.Core.Entities.City", b =>
                {
                    b.HasOne("ePreschool.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.HasOne("ePreschool.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("ePreschool.Core.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("ePreschool.Core.Entities.BusinessUnit", "CurrentBusinessUnit")
                        .WithMany()
                        .HasForeignKey("CurrentBusinessUnitId");

                    b.HasOne("ePreschool.Core.Entities.Preschool", "Preschool")
                        .WithMany()
                        .HasForeignKey("PreschoolId");

                    b.Navigation("City");

                    b.Navigation("CurrentBusinessUnit");

                    b.Navigation("Preschool");
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUserClaim", b =>
                {
                    b.HasOne("ePreschool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUserLogin", b =>
                {
                    b.HasOne("ePreschool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("ePreschool.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationRoleId");

                    b.HasOne("ePreschool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("ePreschool.Core.Entities.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("ePreschool.Core.Entities.Preschool", "Preschool")
                        .WithMany()
                        .HasForeignKey("PreschoolId");

                    b.HasOne("ePreschool.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ePreschool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessUnit");

                    b.Navigation("Preschool");
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUserToken", b =>
                {
                    b.HasOne("ePreschool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ePreschool.Core.Entities.Preschool", b =>
                {
                    b.Navigation("BusinessUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
